language: node_js
node_js:
  - 10

addons:
  sonarcloud:
    organization: "henrythasler"
    
script:
  # - npm run test && sonar-scanner 
  - npm run build
  
after_success:  
  - ls -la
  # - coveralls < coverage/lcov.info

# before_deploy:
  # - npm run build

deploy:
  skip_cleanup: true
  on:
    tags: true  
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
